### ISSUE TITLE
使用demo程序 蓝牙连接异常

### ISSUE THREAD

**Issue by zhenbeiju** [Ginshell/bongSDK-android#2]
如题
直接运行demo程序连接bongX

**Comment by zhenbeiju** [comment]
同一台手机中使用BongT 可以正常操作bong手环

**Comment by sephyioth** [comment]
Dear:
	什么意思？

	

	Thanks
	By sephyioth (凌志)

**Comment by glzjin** [comment]
bong X 的话- -公开的sdk目前貌似操作不了的- - 不过你可以看看我的这个项目 https://gitcafe.com/glzjin/Openbong 里面有提到如何在不断开 bong X 和 手机上 bong APP 的连接的情况下第三者插足操作 bong X~
------------------------------------------------------------------发件人：zhanglin <notifications@github.com>发送时间：2015年7月17日(星期五) 16:35收件人：Ginshell/bongSDK-android <bongSDK-android@noreply.github.com>主　题：[bongSDK-android] 使用demo程序 蓝牙连接异常 (#2)
如题

直接运行demo程序连接bongX

**Comment by zhenbeiju** [comment]
@glzjin  谢谢，我明天试试，手环今天忘在家里了，

**Comment by zhenbeiju** [comment]
@sephyioth 就是demo程序无法除了可以登录成功，别的操作都没有执行结果的

**Comment by glzjin** [comment]
是的，因为目前SDK没改= =需要改改拿实例的方式
2015年7月21日 下午1:25于 zhanglin <notifications@github.com>写道：@sephyioth 就是demo程序无法除了可以登录成功，别的操作都没有执行结果的

**Comment by zhenbeiju** [comment]
@glzjin  在gitcafe上提交了一个工单 你的项目少了两个jar包

**Comment by glzjin** [comment]
额= =找找吧 开源的 稍等我看看
2015年7月21日 下午1:48于 zhanglin <notifications@github.com>写道：@glzjin  在gitcafe上提交了一个工单 你的项目少了两个jar包

**Comment by zhenbeiju** [comment]
@glzjin 恩
finding

**Comment by glzjin** [comment]
已经补上 src libs
2015年7月21日 下午1:48于 zhanglin <notifications@github.com>写道：@glzjin  在gitcafe上提交了一个工单 你的项目少了两个jar包

**Comment by zhenbeiju** [comment]
发现问题的原因了，同时只能有一个手机的一个app和bong手环链接,
最开始的时候demo和bongT 冲突，

**Comment by glzjin** [comment]
是的，但也还是有办法的
2015年7月21日 下午4:52于 zhanglin <notifications@github.com>写道：发现问题的原因了，同时只能有一个手机的一个app和bong手环链接,
最开始的时候demo和bongT 冲突，

**Comment by zhenbeiju** [comment]
@glzjin  我再按照你的方式试试 ，

**Comment by zhenbeiju** [comment]
@sephyioth  麻烦问问iOS的SDK是否支持连接到bong手环 ，我们这边还是链接失败
